package moram.moram.service;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import moram.moram.dao.IMoramDao;
import moram.moram.dao.MoramDaoImpl;
import moram.vo.AttachVO;
import moram.vo.BoardVO;
import moram.vo.DeleteMoramMemberVO;
import moram.vo.MoramMemberVO;
import moram.vo.MoramPreferVO;
import moram.vo.MoramVO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MoramServiceImpl.java
//  @ Date : 2021-12-16
//  @ Author : 
//
//




public class MoramServiceImpl implements IMoramService{
	private static IMoramService service;
	private IMoramDao dao;
	private MoramServiceImpl() {
		dao = MoramDaoImpl.getInstance();
	}

	
	public static IMoramService getInstance() {
		if(service == null)service = new MoramServiceImpl();
			
		
		return service;
	
	}



	@Override
	public String insertMoram(MoramVO vo) {
		String res = null;
		
		try {
			res = dao.insertMoram(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}



	@Override
	public int moramSubscribeChk(String memId) {
		int res = 0;
		
		try {
			res = dao.moramSubscribeChk(memId);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}



	@Override
	public int moramNameChk(String mrname) {
		int res = 0;
		try {
			res = dao.moramNameChk(mrname);
		} catch (SQLException e) {
			res = 0;
			e.printStackTrace();
		}
		return res;
	}



	@Override
	public List<MoramVO> myMoramList(String memId) {
		List<MoramVO> list = null;
		try {
			list = dao.myMoramList(memId);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return list;
	}



	@Override
	public List<MoramVO> preferMoramList(String memId) {
		List<MoramVO> list = null;
		try {
			list = dao.preferMoramList(memId);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return list;
	}



	// 관심모람에 추가
	@Override
	public void insertMoramPrefer(MoramPreferVO vo) {
		try {
			dao.insertMoramPrefer(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}




	@Override
	public List<MoramVO> selCatMoramList(int catNo) {
		List<MoramVO> list = null;
		
		try {
			list = dao.selCatMoramList(catNo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return list;
	}


	@Override
	public List<MoramVO> sameCatMoramList(String memId) {
		List<MoramVO> list = null;
		
		try {
			list = dao.sameCatMoramList(memId);
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		return list;
	}


	@Override
	public MoramVO moraminfo(String mrNo) {
		MoramVO vo = null;
		
		try {
			vo = dao.moraminfo(mrNo);
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		
		return vo;
	}


	@Override
	public int moramMemChk(DeleteMoramMemberVO vo) {
		int res = 0;
		
		try {
			res = dao.moramMemChk(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return res;
	}


	@Override
	public String insertMoramMember(MoramMemberVO vo) {
		String res = null;
		
		try {
			res = dao.insertMoramMember(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}


	@Override
	public int deleteMoramMember(DeleteMoramMemberVO vo) {
		int res = 0;
		
		try {
			res = dao.deleteMoramMember(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}
	
	


	@Override
	public int updateMoraminfo(MoramVO vo) {
		int res = 0;
		try {
			res = dao.updateMoraminfo(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return res;
	}



	@Override
	public void moramInvite() {
		// TODO Auto-generated method stub
		
	}


	@Override
	public List<BoardVO> getCalendar(String moramId) {
		
		List<BoardVO> list = new ArrayList<BoardVO>();
		try {
			list = dao.getCalendar(moramId);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return list;
	}


	@Override
	public int moramMemCnt(String mrNo) {
		int res = 0;
		
		try {
			res = dao.moramMemCnt(mrNo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		return res;
	}


	@Override
	public List<MoramMemberVO> getAllMorami(String moramId) {
		List<MoramMemberVO> list = null;
		try {
			list = dao.getAllMorami(moramId);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return list;
	}


	@Override
	public int MoramjigiChk(MoramMemberVO vo){
		int res = 0;
		
		try {
			res = dao.MoramjigiChk(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}


	@Override
	public int chkMoramPrefer(MoramMemberVO vo) {
		int res = 0;
		
		try {
			res = dao.chkMoramPrefer(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}


	@Override
	public Object moramPrefer(MoramMemberVO vo) {
		Object obj = null;
		
		try {
			obj = dao.moramPrefer(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return obj;
	}


	@Override
	public int moramNotPrefer(MoramMemberVO vo) {
		int res = 0;
		
		try {
			res = dao.moramNotPrefer(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}


	@Override
	public List<AttachVO> imagesList(String mrNo) {
		List<AttachVO> list = null;
		try {
			list = dao.imagesList(mrNo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return list;
	}


	@Override
	public String insertMoramjigi(MoramMemberVO vo) {
		String res = null;
		try {
			res = dao.insertMoramjigi(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return res;
	}


	@Override
	public List<BoardVO> scheduleDetail(BoardVO vo) {
		List<BoardVO> list = null;
		
		try {
			list = dao.scheduleDetail(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return list;
	}


	@Override
	public int moramImgUpdate(MoramVO vo) {
		int res = 0;
		try {
			res = dao.moramImgUpdate(vo);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return res;
	}
	
}
